### ISSUE TITLE
Stremio Docker Image - Remote Access

### ISSUE THREAD

**Issue by Joeharrison94** [n0bodysec/docker-images#7] opened 2023-10-03 09:42 UTC
I am having lots if issues geting this to work, I am running this on a VPS and can access the service but no streams work, I can login and access the addons but any attempt to stream results in this:

![image](https://github.com/n0bodysec/docker-images/assets/53116754/b191dcf2-d7d1-4846-88cd-635119320d91)

I have disabled casting in the env vars, please can you explain the process here, I have tried ip and port access as well as through a vpn tunnel and over fqdn and none work.

**Comment by n0bodysec** [comment] 2023-10-03 16:40
Hello!
This is not a problem with this docker image, but the expected behavior of Stremio Server.

The server has to be accessible via HTTPS, so you need to have a valid SSL certificate. For this same reason, you will need to configure a reverse proxy.

For example, you can use the following configuration:

```
;; A Records
stremio.DOMAIN.TLD.		1	IN	A	THE_IP ; Stremio
stremio-server.DOMAIN.TLD.	1	IN	A	THE_IP ; Stremio Server
```

Then, in your reverse proxy configuration:

```
stremio.DOMAIN.TLD points to stremio:8080 (or 8081 to use the old ui) - With SSL!
stremio-server.DOMAIN.TLD points to stremio:11470 - With SSL!
```

The final step is to enter the Web UI and manually change the URL of the streaming server. You must set it to: `https://stremio-server.DOMAIN.TLD`

**Comment by Joeharrison94** [comment] 2023-10-03 17:31
So in this scenario - expose the port to 11470 

here is my compose (Swag reverse proxy)
```yaml
  stremio
    container_name: stremio
    image: n0bodysec/stremio
    environment:
      WORKDIR: /srv/stremio
      APPLY_PATCHES: 1
      FIX_UNSUPPORTED_MEDIA: 1
      NO_CORS: 1
      CASTING_DISABLED=: 1
    ports:
      - '11470:11470'
      - '12470:12470'
      - '8080:8080'
      - '8081:8081'
    networks:
      - proxy_net
    volumes:
      - $DOCKERDIR/stremio/data:./data/:/root/.stremio-server
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/web/patches.js:ro
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/shell/patches.js:ro
      - $DOCKERDIR/stremio/files/patches:/srv/stremio/patches:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - swag=enable
      - swag_address=stremio
      - swag_port=11470
      - swag_proto=http
      - swag_url=stremio.*
 ```

So in this scenario I go to stremio.domain.com and this will be directed through swag to the container, which gives access to services on 11470, are you saying I must access this over 8080 to use this server I cant use web.stremio.com and point it to my server?

Also I am a little unsure as the stremio docs make it a little unclear, if you run the docker container, in my case this one with CASTING_DISABLED on, as the vps should be a passthrough to the client for it to handle the heavy lifting. Why would you need the web portion if you can use the web.stremio.com one or am I missing something. I cant seem to see how the components hang together as they all have the same ui.

Thanks for the quick response also, I appreciate it.

**Comment by Joeharrison94** [comment] 2023-10-03 17:43
also is there a way to install addons from third parties to the this image?

**Comment by n0bodysec** [comment] 2023-10-03 17:50
> Thanks for the quick response also, I appreciate it.

You are welcome!

I assumed you were trying to use Stremio Web self-hosted in conjunction with Stremio-Server, since this docker image provides both services. Yes, you can use the official Stremio Web instance (https://web.stremio.com) or any other instance.

If you are interested in self-hosting the Stremio server only, then I recommend you the official Stremio image: https://github.com/Stremio/server-docker.


> also is there a way to install addons from third parties to the this image?

Sure! I added support for autoinstall. See https://github.com/n0bodysec/docker-images/issues/5.

I hope this answers all your questions.

**Comment by Joeharrison94** [comment] 2023-10-03 18:16
So I only need to expose the 11470 port via the reverse proxy? I would assume that would be http from the proxy to the stremio port? Then I have one more question, I cant quite get this working when I access the stremio.domain.com it redirects to ```
https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2Fstremio.domain.com#/``` this is inccorect as it prefills http into the streaming server, why also does it go to app.strem.io ?

**Comment by Joeharrison94** [comment] 2023-10-03 19:00
```https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2Fstremio.domain.com#/```

if this is updated to 
```https://app.strem.io/shell-v4.4/?streamingServer=https%3A%2F%2Fstremio.domain.com#/```

then I can do docker logs and see the attempt, but it is trying to cast it even though I set it to disabled?

**Comment by Joeharrison94** [comment] 2023-10-03 19:12
I updated the set url js to set it statically:
```
    // Setting the streaming server URL to a static value
    const staticServerUrl = 'https://stremio.domain.com/';
    console.log(`Setting streaming server url to ${staticServerUrl}`);
    setStreamingServer(staticServerUrl);

```

however it appears that the container is loading it.

compose:

```yaml
  stremio:
    container_name: stremio
    image: n0bodysec/stremio
    hostname: stremio
    environment:
      WORKDIR: /srv/stremio
      APPLY_PATCHES: 1
      FIX_UNSUPPORTED_MEDIA: 1
      NO_CORS: 1
      CASTING_DISABLED: 1
    ports:
      - '11470:11470'
      - '12470:12470'
      - '8080:8080'
      - '8081:8081'
    networks:
      - proxy_net
    volumes:
      - $DOCKERDIR/stremio/data:/root/.stremio-server
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/web/patches.js:ro
      - $DOCKERDIR/stremio/files/patches.js:/srv/stremio/shell/patches.js:ro
      - $DOCKERDIR/stremio/files/patches:/srv/stremio/patches:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - swag=enable
      - swag_address=stremio
      - swag_port=11470
      - swag_proto=http
      - swag_url=stremio.*
```

**Comment by Joeharrison94** [comment] 2023-10-03 19:16
docker logs output:
```
#Applying patches...
Executing patch patches/FIX_UNSUPPORTED_MEDIA.sh
Applying patch for HTTP 415 Unsupported Media Type...
Starting up http-server, serving shell/

http-server version: 14.1.1

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: not visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8081
  http://10.0.10.7:8081
Hit CTRL-C to stop the server

Starting up http-server, serving web/

http-server version: 14.1.1

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: not visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8080
  http://10.0.10.7:8080
Hit CTRL-C to stop the server

hls executables located ->  { ffmpeg: '/usr/bin/ffmpeg', ffsplit: null }
Using app path -> /root/.stremio-server
Cannot update settings Unexpected end of JSON input
(node:15) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
EngineFS server started at http://127.0.0.1:11470
EngineFS HTTPS endpoint at https://local.strem.io:12470
-> GET /
```

**Comment by n0bodysec** [comment] 2023-10-03 20:54
> So I only need to expose the 11470 port via the reverse proxy? I would assume that would be http from the proxy to the stremio port? Then I have one more question, I cant quite get this working when I access the stremio.domain.com it redirects to ` https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2Fstremio.domain.com#/` this is inccorect as it prefills http into the streaming server, why also does it go to app.strem.io ?

No, this is **correct**. Streaming Server MUST start with https://. Also, the redirect to `app.strem.io` is an intended feature from the server.js.

**Comment by Joeharrison94** [comment] 2023-10-03 20:56
> > So I only need to expose the 11470 port via the reverse proxy? I would assume that would be http from the proxy to the stremio port? Then I have one more question, I cant quite get this working when I access the stremio.domain.com it redirects to ` https://app.strem.io/shell-v4.4/?streamingServer=http%3A%2F%2Fstremio.domain.com#/` this is inccorect as it prefills http into the streaming server, why also does it go to app.strem.io ?
> 
> No, this is **correct**. Streaming Server MUST start with https://. Also, the redirect to `app.strem.io` is an intended feature from the server.js.

Ahh thats ok so I just need to work out how to get it to inject https instead of http by default.

I also cant seem to get the patches.js to execute without error its throwing api issues, I noticed https://github.com/Stremio/stremio-web/blob/HEAD/src/types/models/Ctx.d.ts has had an update could this be why it isnt working for me. It tries to execute on web load.

**Comment by Joeharrison94** [comment] 2023-10-03 21:05
whats weird though is that if I use the windows stremio app, and login and enter the stream url os https://stremio.domain.com it connects and streams no issue and I can see it in the docker logs that it is passing through and not attempting to cast it.

**Comment by Joeharrison94** [comment] 2023-10-03 21:18
I know I have bombarded a little here so the recap is

  - The web client (stremio-web.domain.com) fails to run patches.js successfully but nginx is loading it correctly
  - Accessing the web client defaults to http://127.0.0.1:11470/ so I login and update this to the external url https://stremio.domain.com, after adding ```add_header 'Access-Control-Allow-Origin' '*';``` it now loads and plays media
  - Going directly to the server on stremio.domain.com redirects to the https://app.strem.io/ domain but with http in the ref not https, when this is updated and a stream attempted it errors and the console states ```Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.```

**Comment by n0bodysec** [comment] 2023-10-03 21:47
> I know I have bombarded a little here so the recap is
> 
> * The web client (stremio-web.domain.com) fails to run patches.js successfully but nginx is loading it correctly.
> * Accessing the web client defaults to http://127.0.0.1:11470/ so I login and update this to the external url https://stremio.domain.com, after adding `add_header 'Access-Control-Allow-Origin' '*';` it now loads and plays media.
> * Going directly to the server on stremio.domain.com redirects to the https://app.strem.io/ domain but with http in the ref not https, when this is updated and a stream attempted it errors and the console states `Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

1. I updated the patches.js few hours ago to update the settings class. It should work.
2. You can use `NO_CORS` env.
3. It's working as expected. You may need to edit server.js if you want a custom behaviour. Please remember to disable CORS (Stremio Server issue).

**Comment by Joeharrison94** [comment] 2023-10-03 21:55
> > I know I have bombarded a little here so the recap is
> > 
> > * The web client (stremio-web.domain.com) fails to run patches.js successfully but nginx is loading it correctly.
> > * Accessing the web client defaults to http://127.0.0.1:11470/ so I login and update this to the external url https://stremio.domain.com, after adding `add_header 'Access-Control-Allow-Origin' '*';` it now loads and plays media.
> > * Going directly to the server on stremio.domain.com redirects to the https://app.strem.io/ domain but with http in the ref not https, when this is updated and a stream attempted it errors and the console states `Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`
> 
>     1. I updated the patches.js few hours ago to update the settings class. It should work.
> 
>     2. You can use `NO_CORS` env.
> 
>     3. It's working as expected. You may need to edit server.js if you want a custom behaviour. Please remember to disable CORS (Stremio Server issue).

The patches.js is the same as your current one and the console states these two errors:
[STREMIO PATCHER] Qt API not found patches.js:19:16
[STREMIO PATCHER] Error: window.cast api not available

I have enabled the env var but and set it to 1 and I have checked in the container that it is set as such but still throws the CORS error. I dont know why it is not working and respecting it.

**Comment by Joeharrison94** [comment] 2023-10-03 21:56
CORS missing allow origin is what it says upon stream.

**Comment by Joeharrison94** [comment] 2023-10-03 21:57
but remote server in windows app works like a dream oddly just in browser it fails through both web and server directly.

**Comment by n0bodysec** [comment] 2023-10-03 22:38
Please remember that you need to build the stremio image yourself if you want to use the latest `patches.js`. Otherwise, you will need to use an older revision.

Latest `patches.js` (you need to rebuild the docker image): https://gist.github.com/n0bodysec/2896438d8578f13c4a9e30373f7200c1/0f68db07879e8cb5312af0e95935ec3dbfe07578

Previous revision (for the published `n0bodysec/stremio` image): https://gist.github.com/n0bodysec/2896438d8578f13c4a9e30373f7200c1/5e0d98e72bd6277bc9163643fbf3ac2511051259

For ease of use, I recommend the following configuration on your reverse proxy:

- `stremio.domain.tld` pointing to `stremio:8080` or `stremio:8081` - If you want to use the included web server.
- `stremio-server.domain.tld` pointing to `stremio:11470` - This is the server itself.

Next, you have to set your instance's server url to: `https://stremio-server.domain.tld`. You can use the included web server or any other public/private instance (like https://web.strem.io or https://app.strem.io).

**Comment by Joeharrison94** [comment] 2023-10-03 22:47
ahh ok well that makes a lot more sense why the js was failing, so I can use your custom build with the js to auto setup the web ui with everything ready etc. But the only purpose for the server is to stream for the web or using the other public instances as they natively cant stream without it, only for access. I only have one question and that is ifyou make the server public, how do you secure it, normally I would lock it down but I cant see a way to do this given the nature of it.

**Comment by n0bodysec** [comment] 2023-10-04 02:23
The Web UI only serves as a "bridge" to show the end user (you) the content processed by the server. So you always need both services. Of course you can use a public Web UI instance since it doesn't really matter. The server is actually processing the video data.

Regarding how to secure the server, that issue is out of scope. The Stremio Server was not designed to be publicly accessible. If you really really want to make it publicly accesible, I recommend you to define some access rules in your reverse proxy.

This docker image is intended for use on a LAN network.

**Comment by Joeharrison94** [comment] 2023-10-04 05:53
Not a problem what about over a vpn ?

**Comment by n0bodysec** [comment] 2023-10-04 06:05
It's up to you. You can use the method you prefer to secure the server. That is out of the scope of this image.

**Closed** 2023-10-04 06:08 UTC
Labels: invalid, question, stremio
